<?php

namespace App\Services;

use Generator;
use RuntimeException;

class LegacySqlDumpParser
{
    /**
     * Parse the INSERT statements generated by phpMyAdmin into table rows.
     *
     * @return array<string, array<int, array<string, mixed>>>
     */
    public function parse(string $path): array
    {
        if (! is_file($path) || ! is_readable($path)) {
            throw new RuntimeException("Dump SQL não encontrado ou sem permissão de leitura: {$path}");
        }

        $sql = file_get_contents($path);
        if ($sql === false) {
            throw new RuntimeException("Não foi possível ler o dump SQL: {$path}");
        }

        if (! mb_check_encoding($sql, 'UTF-8')) {
            throw new RuntimeException('O dump SQL não está codificado em UTF-8.');
        }

        $tables = [];

        foreach ($this->insertStatements($sql) as $statement) {
            if (! preg_match(
                '/^INSERT\s+INTO\s+`([^`]+)`\s*\((.*?)\)\s*VALUES\s*(.*);\s*$/si',
                trim($statement),
                $matches,
            )) {
                continue;
            }

            $table = $matches[1];
            $columns = array_map(
                static fn (string $column): string => trim($column, " \t\n\r\0\x0B`"),
                explode(',', $matches[2]),
            );

            foreach ($this->parseRows($matches[3]) as $values) {
                if (count($columns) !== count($values)) {
                    throw new RuntimeException(
                        "Quantidade de colunas incompatível em {$table}: ".count($columns).' colunas e '.count($values).' valores.'
                    );
                }

                $tables[$table][] = array_combine($columns, $values);
            }
        }

        return $tables;
    }

    /** @return Generator<int, string> */
    private function insertStatements(string $sql): Generator
    {
        $offset = 0;
        $length = strlen($sql);

        while (($start = stripos($sql, 'INSERT INTO', $offset)) !== false) {
            $inQuote = false;
            $escaped = false;

            for ($index = $start; $index < $length; $index++) {
                $character = $sql[$index];

                if ($inQuote) {
                    if ($escaped) {
                        $escaped = false;
                        continue;
                    }

                    if ($character === '\\') {
                        $escaped = true;
                        continue;
                    }

                    if ($character === "'") {
                        if (($sql[$index + 1] ?? null) === "'") {
                            $index++;
                            continue;
                        }

                        $inQuote = false;
                    }

                    continue;
                }

                if ($character === "'") {
                    $inQuote = true;
                    continue;
                }

                if ($character === ';') {
                    yield substr($sql, $start, ($index - $start) + 1);
                    $offset = $index + 1;
                    continue 2;
                }
            }

            throw new RuntimeException('O dump contém um INSERT sem terminador.');
        }
    }

    /** @return array<int, array<int, mixed>> */
    private function parseRows(string $valuesSql): array
    {
        $rows = [];
        $row = [];
        $buffer = '';
        $inRow = false;
        $inQuote = false;
        $quotedValue = false;
        $length = strlen($valuesSql);

        for ($index = 0; $index < $length; $index++) {
            $character = $valuesSql[$index];

            if ($inQuote) {
                if ($character === '\\') {
                    $next = $valuesSql[++$index] ?? '';
                    $buffer .= match ($next) {
                        '0' => "\0",
                        'n' => "\n",
                        'r' => "\r",
                        't' => "\t",
                        'Z' => chr(26),
                        default => $next,
                    };
                    continue;
                }

                if ($character === "'") {
                    if (($valuesSql[$index + 1] ?? null) === "'") {
                        $buffer .= "'";
                        $index++;
                        continue;
                    }

                    $inQuote = false;
                    continue;
                }

                $buffer .= $character;
                continue;
            }

            if (! $inRow) {
                if ($character === '(') {
                    $inRow = true;
                    $row = [];
                    $buffer = '';
                    $quotedValue = false;
                }

                continue;
            }

            if ($character === "'") {
                if (trim($buffer) === '') {
                    $buffer = '';
                }
                $inQuote = true;
                $quotedValue = true;
                continue;
            }

            if ($character === ',') {
                $row[] = $this->normalizeValue($buffer, $quotedValue);
                $buffer = '';
                $quotedValue = false;
                continue;
            }

            if ($character === ')') {
                $row[] = $this->normalizeValue($buffer, $quotedValue);
                $rows[] = $row;
                $row = [];
                $buffer = '';
                $quotedValue = false;
                $inRow = false;
                continue;
            }

            $buffer .= $character;
        }

        if ($inQuote || $inRow) {
            throw new RuntimeException('O dump contém uma lista de valores incompleta.');
        }

        return $rows;
    }

    private function normalizeValue(string $value, bool $quoted): mixed
    {
        if ($quoted) {
            return $value;
        }

        $value = trim($value);

        if (strcasecmp($value, 'NULL') === 0) {
            return null;
        }

        if (preg_match('/^-?\d+$/', $value)) {
            return (int) $value;
        }

        if (is_numeric($value)) {
            return (float) $value;
        }

        return $value;
    }
}
