<?php

return [
    /* Categorias exibidas no cadastro, na edição e nos filtros de serviços. */
    'service_categories' => [
        'Açougue',
        'Advogado',
        'Aluga Cadeiras e Mesas',
        'Artes Personalizadas',
        'Ateliê',
        'Cabeleireira',
        'Cantores e Bandas',
        'Carro de Mudança',
        'Carroceiro',
        'Cartomante',
        'Cartório',
        'Chaveiro',
        'Confeitaria',
        'Conserto de Portão',
        'Consertos de Eletrodomésticos',
        'Consertos de TV e Som',
        'Costureira',
        'Dentista',
        'Designer de Sobrancelhas',
        'Diarista',
        'Editor de Fotos',
        'Eletricista',
        'Empréstimos e Serviços',
        'Encanador',
        'Enfermeira(o)',
        'Entregador',
        'Entregador de Gás',
        'Faxineira',
        'Faxineira / Diarista',
        'Faz Tudo - Serviços Residenciais',
        'Fisioterapeuta',
        'Forro de PVC',
        'Fotógrafo',
        'Frete e Mudanças',
        'Gesseiro',
        'Gráficas',
        'Guincho',
        'Instalação de Portas e Janelas',
        'Instalador de Antenas',
        'Instalador de Ar-condicionado',
        'Instrutor Autônomo de Carro e Moto',
        'Jardineiro',
        'Lava Jato',
        'Locação de Kits para Festas',
        'Lojas',
        'Manicure e Pedicure',
        'Marceneiro',
        'Marcenaria',
        'Maquiadora',
        'Material de Construção',
        'Mecânico',
        'Montador de Móveis',
        'Moto Táxi',
        'Móveis Planejados',
        'Óticas em Nossa Senhora da Glória',
        'Ônibus de Viagens',
        'Pedreiro',
        'Pedreiro de Acabamento',
        'Personalizados, Artes Sublimadas e Logos',
        'Pintor',
        'Pizzaria',
        'Plotagem',
        'Portões e Manutenção',
        'Pousada e Hotel',
        'Programador',
        'Prótese Dentária',
        'Provedor de Internet',
        'Reformas e Fabricação de Estofados',
        'Restaurante',
        'Restaurante / Pizzaria',
        'Soldador',
        'Tatuador',
        'Taxista',
        'Taxista - Viagens para Aracaju',
        'Taxista - Viagens para Itabaiana',
        'Técnica de Enfermagem',
        'Técnico de Informática',
        'Técnico em Eletrônica',
        'TI / Informática',
        'Uber',
        'Vendedora de Refrigeração Comercial e Industrial',
    ],

    /*
    |--------------------------------------------------------------------------
    | Limites de perfis profissionais por plano
    |--------------------------------------------------------------------------
    |
    | Use null para planos sem limite. Os planos pagos exibidos atualmente no
    | site anunciam perfis/anúncios ilimitados, por isso permanecem sem limite.
    |
    */
    'professional_profile_limits' => [
        'free'         => 1,
        'start'        => 1,
        'pro'          => null,
        'professional' => null,
        'profissional' => null,
        'enterprise'   => null,
        'premium'      => null,
        'gold'         => null,
        'ouro'         => null,
    ],

    /*
    | Limites de lojas simultâneas por plano.
    | null = ilimitado | 0 = sem loja | inteiro = limite
    */
    'store_limits' => [
        'free'         => 0,
        'start'        => 1,
        'pro'          => 1,
        'professional' => 1,
        'profissional' => 1,
        'enterprise'   => 3,
        'premium'      => 3,
        'gold'         => 3,
        'ouro'         => 3,
    ],

    'store_product_limits' => [
        'free'         => 0,
        'start'        => 30,
        'pro'          => null,
        'professional' => null,
        'profissional' => null,
        'enterprise'   => null,
        'premium'      => null,
        'gold'         => null,
        'ouro'         => null,
    ],

    'plan_labels' => [
        'free'         => 'Gratuito',
        'start'        => 'Start',
        'pro'          => 'PRO',
        'professional' => 'PRO',
        'profissional' => 'PRO',
        'enterprise'   => 'Premium',
        'premium'      => 'Premium',
        'gold'         => 'Premium',
        'ouro'         => 'Premium',
    ],

    'store_featured_enabled' => [
        'free'         => false,
        'start'        => false,
        'pro'          => true,
        'professional' => false,
        'profissional' => false,
        'enterprise'   => true,
        'premium'      => true,
        'gold'         => true,
        'ouro'         => true,
    ],

    'store_featured_default_days' => 30,

    'provider_featured_enabled' => [
        'free'         => false,
        'start'        => true,
        'pro'          => true,
        'professional' => true,
        'profissional' => true,
        'enterprise'   => true,
        'premium'      => true,
        'gold'         => true,
        'ouro'         => true,
    ],

    'store_media_limits' => [
        'free'         => ['banners' => 0, 'gallery' => 0],
        'start'        => ['banners' => 1, 'gallery' => 5],
        'pro'          => ['banners' => 3, 'gallery' => 12],
        'professional' => ['banners' => 3, 'gallery' => 12],
        'profissional' => ['banners' => 3, 'gallery' => 12],
        'enterprise'   => ['banners' => 6, 'gallery' => 20],
        'premium'      => ['banners' => 6, 'gallery' => 20],
        'gold'         => ['banners' => 6, 'gallery' => 20],
        'ouro'         => ['banners' => 6, 'gallery' => 20],
    ],

    'store_analytics_period_days' => [
        'free'         => 7,
        'start'        => 30,
        'pro'          => 60,
        'professional' => 30,
        'profissional' => 30,
        'enterprise'   => 90,
        'premium'      => 90,
        'gold'         => 90,
        'ouro'         => 90,
    ],

    /*
    | Quantidade máxima de promoções simultaneamente ativas por plano.
    */
    'store_promotion_limits' => [
        'free'         => 0,
        'start'        => 2,
        'pro'          => 5,
        'professional' => 5,
        'profissional' => 5,
        'enterprise'   => 10,
        'premium'      => 10,
        'gold'         => 10,
        'ouro'         => 10,
    ],

    /* Grupos locais exibidos na página inicial, na ordem definida abaixo. */
    'home_city_groups' => [
        1 => ['city' => 'Aracaju', 'gentilic' => 'aracajuense', 'cover' => 'Cidades/Aracaju.webp'],
        2 => ['city' => 'Tobias Barreto', 'gentilic' => 'tobiense', 'cover' => 'Cidades/Tobias Barreto.webp'],
        3 => ['city' => 'Itabaiana', 'gentilic' => 'itabaianense', 'cover' => 'Cidades/Itabaiana.webp'],
        4 => ['city' => 'Nossa Senhora da Glória', 'gentilic' => 'gloriense', 'cover' => 'Cidades/Nossa Senhora da Glória.webp'],
        5 => ['city' => 'Canindé de São Francisco', 'gentilic' => 'canindeense', 'cover' => 'Cidades/Canindé de São Francisco.webp'],
        6 => ['city' => 'Monte Alegre de Sergipe', 'gentilic' => 'monte-alegrense', 'cover' => 'Cidades/Monte Alegre.webp'],
        7 => ['city' => 'Nossa Senhora das Dores', 'gentilic' => 'dorense', 'cover' => 'Cidades/Nossa Senhora das  Dores.webp'],
    ],
];
